[phases.setup]
nixPkgs = ["...", "chromium"]

[phases.install]
cmds = [
    "pnpm install --frozen-lockfile",
    "pnpm exec playwright install chromium"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node .next/standalone/server.js"
