[phases.setup]
nixPkgs = ["...", "glib", "nss", "nspr", "atk", "at-spi2-atk", "cups", "gtk3", "pango", "cairo", "dbus", "libdrm", "mesa", "xorg.libX11", "xorg.libxcb", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxshmfence", "expat", "alsa-lib"]

[phases.install]
cmds = [
    "pnpm install --frozen-lockfile",
    "pnpm exec playwright install chromium",
    "pnpm exec playwright install-deps chromium"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node .next/standalone/server.js"
